# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserBrewFish < Formula
  desc "Different type of projects, not big enough to warrant a separate repo."
  homepage "https://github.com/dirien/quick-bites"
  version "0.1"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dirien/quick-bites/releases/download/0.1/goreleaser-brew-fish_0.1_darwin_arm64.tar.gz"
      sha256 "81ab401017f58e5bc60fa107956913fdd40af87df9fda94175c337c6f47bf9fd"

      def install
        bin.install "goreleaser-brew-fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dirien/quick-bites/releases/download/0.1/goreleaser-brew-fish_0.1_darwin_amd64.tar.gz"
      sha256 "27561541924b7213613ad273f9262305464b7789bfa4bd73b406f3bfd32d17be"

      def install
        bin.install "goreleaser-brew-fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirien/quick-bites/releases/download/0.1/goreleaser-brew-fish_0.1_linux_arm64.tar.gz"
      sha256 "4b275219499f090d968f4a2f4909d84cc6e2713fa8798775c35aa5b3ce318ff1"

      def install
        bin.install "goreleaser-brew-fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dirien/quick-bites/releases/download/0.1/goreleaser-brew-fish_0.1_linux_amd64.tar.gz"
      sha256 "e984af4919a5a9b55243c42421fd82643b38e14bb35ffdf98d45cdedddb013a6"

      def install
        bin.install "goreleaser-brew-fish"
      end
    end
  end
end
